replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/user-service
  tag: "development-10acadb"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
  grpcPort: 9090
istio:
  enabled: true
  host: "user-service"
  mtls:
    mode: STRICT
  authorization:
    internalCallers:
      - "cluster.local/ns/fitnest-dev/sa/identity-service"
      - "cluster.local/ns/fitnest-dev/sa/payment-service"
      - "cluster.local/ns/fitnest-dev/sa/api-gateway"
      - "cluster.local/ns/fitnest-dev/sa/storage-service"
      - "cluster.local/ns/fitnest-dev/sa/catalog-service"
hpa:
  enabled: false
  minReplicas: "1"
  maxReplicas: "3"
  cpuUtilization: "90"
  memoryUtilization: "450Mi"
jwt:
  secret: "your-jwt-secret-change-in-production"
env:
  SPRING_PROFILES_ACTIVE: dev
  SPRINGDOC_SERVER_URL: "https://dev-api.fitnest.az"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-user:5432/fitnest_user?sslmode=disable"
  SPRING_DATASOURCE_USERNAME: "fitnest_user"
  SPRING_DATASOURCE_PASSWORD: "user_password_123"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  LOGGING_LEVEL_ROOT: INFO
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_PASSWORD: ""
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  JWT_SECRET: "your-jwt-secret-change-in-production"
  JWT_ISSUER: "fitnest"
  IDENTITY_SERVICE_URL: "http://identity-service:8080"
  JAVA_OPTS: "-Xmx480m -Xms256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xss256k"
resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    cpu: 250m
    memory: 256Mi
