replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/user-service
  tag: "0c891d8"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
istio:
  enabled: true
  host: "user-service"
env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-user:5432/fitnest_user"
  SPRING_DATASOURCE_USERNAME: "fitnest_user"
  SPRING_DATASOURCE_PASSWORD: "user_password_123"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_REDIS_HOST: "redis.fitnest-dev.svc.cluster.local"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_PASSWORD: ""
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.fitnest-dev.svc.cluster.local:9092"
  IAM_SERVICE_URL: "http://iam-service:8080"
  MEDIA_SERVICE_URL: "http://media-service:8080"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
