replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/user-service
  tag: "development-c4ad842"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
istio:
  enabled: true
  host: "user-service"
  mtls:
    mode: STRICT
env:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-user.fitnest-dev.svc.cluster.local:5432/fitnest_user?sslmode=disable"
  SPRING_DATASOURCE_USERNAME: "fitnest_user"
  SPRING_DATASOURCE_PASSWORD: "user_password_123"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  LOGGING_LEVEL_AZ_FITNEST_USER_USER_ADAPTER_PERSISTENCE: INFO
  LOGGING_LEVEL_AZ_FITNEST_USER_USER_ADAPTER_CLIENT: DEBUG
  SPRING_REDIS_HOST: "redis.fitnest-dev.svc.cluster.local"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_PASSWORD: ""
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.fitnest-dev.svc.cluster.local:9092"
  JWT_SECRET: "your-jwt-secret-change-in-production"
  JWT_ISSUER: "fitnest"
  IAM_SERVICE_URL: "http://iam-service:8080"
  MEDIA_SERVICE_URL: "http://media-service:8086"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
