apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "user-service.fullname" . } }
  labels:
    { { - include "user-service.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      { { - include "user-service.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels:
        { { - include "user-service.selectorLabels" . | nindent 8 } }
      annotations:
        { { - if .Values.istio.enabled } }
        sidecar.istio.io/inject: "true"
        { { - end } }
    spec:
      serviceAccountName: { { include "user-service.fullname" . } }
      { { - with .Values.image.imagePullSecrets } }
      imagePullSecrets:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.port } }
              protocol: TCP
          { { - if .Values.env } }
          env:
          { { - range $key, $value := .Values.env } }
          - name: { { $key } }
            value: { { $value | quote } }
          { { - end } }
          { { - end } }
          { { - if .Values.livenessProbe } }
          livenessProbe:
            { { - toYaml .Values.livenessProbe | nindent 10 } }
          { { - end } }
          { { - if .Values.readinessProbe } }
          readinessProbe:
            { { - toYaml .Values.readinessProbe | nindent 10 } }
          { { - end } }
          resources:
            { { - toYaml .Values.resources | nindent 10 } }
